baseURL = 'https://rxbxn.be/'
languageCode = 'en-us'
title = 'Asssorted Writings'
theme = "hermit-v2"

[params]
   description = "Writing as speaking makes me sleepy."
   author = { name = "Kneecrust", email = "ruben@kneecrust.com" }
   enableGitInfo = true

[frontmatter]
   date = ["date", "publishDate", "lastmod"]
   lastmod = ["lastmod", ":git", "date", "publishDate"]