baseURL = 'https://rxbxn.be/'
languageCode = 'en-us'
title = "What else but Curiosity"

theme = "hermit-v2"

[params]
   homeSubtitle = "Written because talking was too much."
   description = "Written because talking was too much."
   author = { name = "Kneecrust", email = "ruben@kneecrust.com" }
   enableGitInfo = true
   dateform        = "Jan 2, 2006"
   dateformShort   = "Jan 2"
   dateformNum     = "2006-01-02"
   dateformNumTime = "2006-01-02 15:04 -0700"

   themeColor = "#403c37"
   accentColor = "#ab3d2e"

   homeSubtitlePrinter = true
   scrollToTop = true 
   footerHideThemeName = true

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

[frontmatter]
   date = ["date", "publishDate", "lastmod"]
   lastmod = ["lastmod", ":git", "date", "publishDate"]